from datetime import date

PERIOD_START = date(2024, 3, 1)
PERIOD_END = date(2024, 3, 31)

TOTAL_CLEAN_TRANSACTIONS = 185

SETTLEMENT_DAYS = {
    "card": (1, 2),
}

AMOUNT_TOLERANCE_CENTS = 1
DATE_WINDOW_DAYS = 3

ROUNDING_TXN_COUNT = 12

RANDOM_SEED = 42

FEE_RATE_PERCENT = 2.9
BUSINESS_HOURS_START = 8
BUSINESS_HOURS_END = 20
